"""
Run codesight separately on each code module of this project and consolidate
outputs under .codesight/.

This wiki project mixes content (wiki/, raw/, docs/) with code (tools/, web/).
codesight 1.10's .codesightignore is not respected when scanning the project
root, so we drive it explicitly: one scan per code directory.

Usage:
  python tools/codesight_scan.py        # scan + write to .codesight/
  python tools/codesight_scan.py --html # also generate HTML report
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_ROOT = PROJECT_ROOT / ".codesight"

# Code modules to scan. Each entry: (label, source_dir)
MODULES = [
    ("tools", PROJECT_ROOT / "tools"),
    ("web", PROJECT_ROOT / "web"),
]


def run_npx(args: list[str]) -> int:
    """Run npx codesight with the given arguments. Returns exit code."""
    cmd = ["npx", "--yes", "codesight", *args]
    print(f"  $ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=PROJECT_ROOT, shell=True)
    return result.returncode


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--html", action="store_true", help="Also generate HTML report")
    parser.add_argument("--clean", action="store_true", help="Remove existing .codesight/ first")
    args = parser.parse_args()

    if args.clean and OUTPUT_ROOT.exists():
        print(f"Removing {OUTPUT_ROOT}...")
        shutil.rmtree(OUTPUT_ROOT, ignore_errors=True)

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

    summary_lines = ["# Codesight Scan Results", "",
                     f"_Generated by `tools/codesight_scan.py`_", ""]

    for label, src in MODULES:
        if not src.exists():
            print(f"  SKIP {label}: {src} does not exist")
            continue
        out_dir = OUTPUT_ROOT / label
        out_dir.mkdir(parents=True, exist_ok=True)

        print(f"\n=== Scanning {label} ({src.relative_to(PROJECT_ROOT)}) ===")
        # codesight 1.10 bug: -o resolves relative to the scanned dir, and an
        # absolute path gets prepended to the scan dir. Workaround: write to
        # the source dir's local .codesight/, then move it to OUTPUT_ROOT/{label}/
        scan_args = [str(src)]
        if args.html:
            scan_args.append("--html")
        rc = run_npx(scan_args)
        if rc != 0:
            print(f"  WARN: codesight returned exit code {rc} for {label}")
            summary_lines.append(f"- ⚠ **{label}** — scan failed (exit {rc})")
            continue

        # Move src/.codesight/* to OUTPUT_ROOT/{label}/
        local_out = src / ".codesight"
        if local_out.exists():
            for item in local_out.iterdir():
                target = out_dir / item.name
                if target.exists():
                    if target.is_dir():
                        shutil.rmtree(target)
                    else:
                        target.unlink()
                shutil.move(str(item), str(target))
            shutil.rmtree(local_out, ignore_errors=True)

        # Read main output for summary
        main_md = out_dir / "CODESIGHT.md"
        if main_md.exists():
            text = main_md.read_text(encoding="utf-8", errors="replace")
            # Try to extract token-savings line and stack line
            lines = text.splitlines()
            stack = next((l for l in lines if l.startswith("> **Stack:")), "")
            stats = next((l for l in lines if "routes" in l and "models" in l), "")
            summary_lines.append(f"## {label}")
            summary_lines.append("")
            summary_lines.append(f"- Output: [`{out_dir.relative_to(PROJECT_ROOT)}/CODESIGHT.md`]({out_dir.relative_to(PROJECT_ROOT)}/CODESIGHT.md)")
            if stack:
                summary_lines.append(f"- {stack.lstrip('> ').strip()}")
            if stats:
                summary_lines.append(f"- {stats.lstrip('> ').strip()}")
            summary_lines.append("")

    summary_md = OUTPUT_ROOT / "README.md"
    summary_md.write_text("\n".join(summary_lines) + "\n", encoding="utf-8")
    print(f"\nSummary written to {summary_md.relative_to(PROJECT_ROOT)}")
    print("Done.")


if __name__ == "__main__":
    main()
