"""
Interview queue manager — for items that require user judgment.

The auto-collection pipeline classifies, evaluates, and dedupes items
automatically, but some items genuinely need a human decision:
  - Is this a duplicate of an existing operation, or a new phase?
  - Does this academic paper warrant a full ingest, or just a citation?
  - Is the source reliability sufficient for a single-source operation page?
  - Does this article describe an actual joint operation or just policy commentary?

Items needing decisions are written to:
  _workspace/interview_queue.md

This tool provides:
  - `add_question(...)` — append a structured question to the queue
  - `list_open()` — list unanswered questions
  - `mark_answered(...)` — record the user's decision and unblock processing
  - CLI for listing/answering interactively
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
INTERVIEW_FILE = PROJECT_ROOT / "_workspace" / "interview_queue.md"
INTERVIEW_STATE = PROJECT_ROOT / "_workspace" / "interview_state.json"


def _load_state() -> dict[str, Any]:
    if INTERVIEW_STATE.exists():
        return json.loads(INTERVIEW_STATE.read_text(encoding="utf-8"))
    return {"questions": []}


def _save_state(state: dict[str, Any]) -> None:
    INTERVIEW_STATE.parent.mkdir(parents=True, exist_ok=True)
    INTERVIEW_STATE.write_text(
        json.dumps(state, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def add_question(
    *,
    item_id: str,
    title: str,
    source: str,
    url: str,
    context: str,
    question: str,
    options: list[str],
    pipeline_stage: str = "evaluator",
    blocks_processing: bool = True,
) -> str:
    """Append a question to the interview queue. Returns the question ID."""
    state = _load_state()
    qid = f"Q{len(state['questions']) + 1:04d}"
    entry = {
        "qid": qid,
        "item_id": item_id,
        "title": title,
        "source": source,
        "url": url,
        "context": context,
        "question": question,
        "options": options,
        "pipeline_stage": pipeline_stage,
        "blocks_processing": blocks_processing,
        "status": "open",
        "answer": None,
        "created_at": datetime.now().isoformat(),
        "answered_at": None,
    }
    state["questions"].append(entry)
    _save_state(state)
    _render_markdown(state)
    return qid


def list_open() -> list[dict[str, Any]]:
    state = _load_state()
    return [q for q in state["questions"] if q["status"] == "open"]


def list_all() -> list[dict[str, Any]]:
    state = _load_state()
    return state["questions"]


def mark_answered(qid: str, answer: str) -> bool:
    state = _load_state()
    for q in state["questions"]:
        if q["qid"] == qid and q["status"] == "open":
            q["status"] = "answered"
            q["answer"] = answer
            q["answered_at"] = datetime.now().isoformat()
            _save_state(state)
            _render_markdown(state)
            return True
    return False


def _render_markdown(state: dict[str, Any]) -> None:
    INTERVIEW_FILE.parent.mkdir(parents=True, exist_ok=True)
    open_qs = [q for q in state["questions"] if q["status"] == "open"]
    answered = [q for q in state["questions"] if q["status"] == "answered"]

    lines = [
        "# Interview Queue — Cybercrime IC Auto-Collection",
        "",
        f"_Last updated: {datetime.now().isoformat()}_",
        "",
        f"**Open questions: {len(open_qs)}** | Answered: {len(answered)}",
        "",
        "Questions are generated by the auto-collection pipeline when an item",
        "requires human judgment. Resolve open questions before running the",
        "integration phase. Each question blocks the corresponding pipeline",
        "item until answered.",
        "",
        "## How to answer",
        "",
        "Use `python tools/interview_queue.py answer <QID> <choice>` or edit",
        "the JSON state at `_workspace/interview_state.json` directly.",
        "",
        "---",
        "",
        "## Open Questions",
        "",
    ]

    if not open_qs:
        lines.append("_No open questions._")
        lines.append("")
    else:
        for q in open_qs:
            lines.append(f"### {q['qid']} — {q['title'][:80]}")
            lines.append("")
            lines.append(f"- **Item**: `{q['item_id']}`")
            lines.append(f"- **Source**: {q['source']}")
            lines.append(f"- **URL**: <{q['url']}>")
            lines.append(f"- **Pipeline stage**: {q['pipeline_stage']}")
            lines.append(f"- **Created**: {q['created_at']}")
            lines.append("")
            lines.append("**Context:**")
            lines.append("")
            lines.append(q["context"])
            lines.append("")
            lines.append(f"**Question:** {q['question']}")
            lines.append("")
            lines.append("**Options:**")
            for i, opt in enumerate(q["options"], 1):
                lines.append(f"- `{chr(96+i)}` — {opt}")
            lines.append("")
            lines.append(f"To answer: `python tools/interview_queue.py answer {q['qid']} <a|b|c|...>`")
            lines.append("")
            lines.append("---")
            lines.append("")

    if answered:
        lines.append("")
        lines.append("## Answered Questions (history)")
        lines.append("")
        for q in answered[-10:]:
            chosen = q["answer"]
            lines.append(f"- **{q['qid']}** — {q['title'][:60]}")
            lines.append(f"  Answer: `{chosen}` (at {q['answered_at']})")
        lines.append("")

    INTERVIEW_FILE.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Interview queue manager")
    sub = parser.add_subparsers(dest="cmd")

    sub.add_parser("list", help="List open questions")
    sub.add_parser("listall", help="List all questions including answered")

    p_answer = sub.add_parser("answer", help="Answer a question")
    p_answer.add_argument("qid")
    p_answer.add_argument("choice", help="Option letter (a, b, c) or free text")

    p_add = sub.add_parser("add", help="Add a test question")
    p_add.add_argument("--item")
    p_add.add_argument("--title")
    p_add.add_argument("--source")
    p_add.add_argument("--url")
    p_add.add_argument("--context")
    p_add.add_argument("--question")
    p_add.add_argument("--options", nargs="+")

    args = parser.parse_args()

    if args.cmd == "list":
        for q in list_open():
            print(f"{q['qid']} [{q['pipeline_stage']}] {q['title'][:70]}")
            print(f"   {q['question']}")
            for i, opt in enumerate(q["options"], 1):
                print(f"     {chr(96+i)}. {opt}")
            print()
    elif args.cmd == "listall":
        for q in list_all():
            print(f"{q['qid']} [{q['status']}] {q['title'][:70]} -> {q.get('answer', '-')}")
    elif args.cmd == "answer":
        ok = mark_answered(args.qid, args.choice)
        print(f"{'✔' if ok else '✘'} {args.qid} -> {args.choice}")
    elif args.cmd == "add":
        qid = add_question(
            item_id=args.item or "test",
            title=args.title or "Test",
            source=args.source or "manual",
            url=args.url or "",
            context=args.context or "",
            question=args.question or "Test?",
            options=args.options or ["yes", "no"],
        )
        print(f"Added {qid}")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
